// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (ProviderAccessToken, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSessionState(ctx context.Context, arg CreateSessionStateParams) (SessionStore, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccessToken(ctx context.Context, groupID int32) error
	DeleteExpiredSessionStates(ctx context.Context) error
	DeleteGroup(ctx context.Context, id int32) error
	DeleteOrganization(ctx context.Context, id int32) error
	DeleteRole(ctx context.Context, id int32) error
	DeleteSessionState(ctx context.Context, id int32) error
	DeleteSessionStateByGroupID(ctx context.Context, grpID sql.NullInt32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAccessTokenByGroupID(ctx context.Context, groupID int32) (ProviderAccessToken, error)
	GetGroupByID(ctx context.Context, id int32) (Group, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	GetGroupIDPortBySessionState(ctx context.Context, sessionState string) (GetGroupIDPortBySessionStateRow, error)
	GetOrganization(ctx context.Context, id int32) (Organization, error)
	GetOrganizationByName(ctx context.Context, name string) (Organization, error)
	GetOrganizationForUpdate(ctx context.Context, name string) (Organization, error)
	GetRoleByID(ctx context.Context, id int32) (Role, error)
	GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (Role, error)
	GetSessionState(ctx context.Context, id int32) (SessionStore, error)
	GetSessionStateByGroupID(ctx context.Context, grpID sql.NullInt32) (SessionStore, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUserName(ctx context.Context, username string) (User, error)
	GetUserClaims(ctx context.Context, id int32) (GetUserClaimsRow, error)
	ListGroups(ctx context.Context, arg ListGroupsParams) ([]Group, error)
	ListGroupsByOrganizationID(ctx context.Context, organizationID int32) ([]Group, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]Role, error)
	ListRolesByGroupID(ctx context.Context, groupID int32) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByRoleID(ctx context.Context, roleID int32) ([]User, error)
	RevokeGroupUsersTokens(ctx context.Context, groupID int32) (User, error)
	RevokeOrganizationUsersTokens(ctx context.Context, organizationID int32) (User, error)
	RevokeRoleUsersTokens(ctx context.Context, roleID int32) (User, error)
	RevokeUserToken(ctx context.Context, id int32) (User, error)
	RevokeUsersTokens(ctx context.Context) (User, error)
	UpdateAccessToken(ctx context.Context, arg UpdateAccessTokenParams) (ProviderAccessToken, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
