// Code generated by MockGen. DO NOT EDIT.
// Source: ./jwtauth.go
//
// Generated by this command:
//
//	mockgen -package mock_auth -destination=./mock/jwtauth.go -source=./jwtauth.go
//

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	reflect "reflect"

	jwk "github.com/lestrrat-go/jwx/v2/jwk"
	openid "github.com/lestrrat-go/jwx/v2/jwt/openid"
	gomock "go.uber.org/mock/gomock"
)

// MockJwtValidator is a mock of JwtValidator interface.
type MockJwtValidator struct {
	ctrl     *gomock.Controller
	recorder *MockJwtValidatorMockRecorder
}

// MockJwtValidatorMockRecorder is the mock recorder for MockJwtValidator.
type MockJwtValidatorMockRecorder struct {
	mock *MockJwtValidator
}

// NewMockJwtValidator creates a new mock instance.
func NewMockJwtValidator(ctrl *gomock.Controller) *MockJwtValidator {
	mock := &MockJwtValidator{ctrl: ctrl}
	mock.recorder = &MockJwtValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtValidator) EXPECT() *MockJwtValidatorMockRecorder {
	return m.recorder
}

// ParseAndValidate mocks base method.
func (m *MockJwtValidator) ParseAndValidate(tokenString string) (openid.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAndValidate", tokenString)
	ret0, _ := ret[0].(openid.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAndValidate indicates an expected call of ParseAndValidate.
func (mr *MockJwtValidatorMockRecorder) ParseAndValidate(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAndValidate", reflect.TypeOf((*MockJwtValidator)(nil).ParseAndValidate), tokenString)
}

// MockKeySetFetcher is a mock of KeySetFetcher interface.
type MockKeySetFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockKeySetFetcherMockRecorder
}

// MockKeySetFetcherMockRecorder is the mock recorder for MockKeySetFetcher.
type MockKeySetFetcherMockRecorder struct {
	mock *MockKeySetFetcher
}

// NewMockKeySetFetcher creates a new mock instance.
func NewMockKeySetFetcher(ctrl *gomock.Controller) *MockKeySetFetcher {
	mock := &MockKeySetFetcher{ctrl: ctrl}
	mock.recorder = &MockKeySetFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeySetFetcher) EXPECT() *MockKeySetFetcherMockRecorder {
	return m.recorder
}

// GetKeySet mocks base method.
func (m *MockKeySetFetcher) GetKeySet() (jwk.Set, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeySet")
	ret0, _ := ret[0].(jwk.Set)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeySet indicates an expected call of GetKeySet.
func (mr *MockKeySetFetcherMockRecorder) GetKeySet() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeySet", reflect.TypeOf((*MockKeySetFetcher)(nil).GetKeySet))
}
