# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
          - "go.opentelemetry.io/contrib*"
          - "github.com/signalfx/splunk-otel-go*"
  - package-ecosystem: "gomod"
    directory: "tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "docs"
    schedule:
      interval: "weekly"
    groups:
      docusaurus:
        patterns:
          - "*docusaurus*"
      eslint:
        patterns:
          - "*eslint*"
    ignore:
      # facebook/docusaurus#4029 suggests MDX v2 will only be in the v3 release.
      # facebook/docusaurus#9053 has some more details on the migration.
      - dependency-name: "@mdx-js/react"
        update-types: ["version-update:semver-major"]
      # facebook/docusaurus#8940 docusaurus uses v1
      - dependency-name: "prism-react-renderer"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
