# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
          - "go.opentelemetry.io/contrib*"
          - "github.com/signalfx/splunk-otel-go*"
      buf:
        patterns:
          - "buf.build/*"
  - package-ecosystem: "gomod"
    # A lot of tools/ ends up generating files or otherwise causing CI breaks.
    # Handle them as a batch at a lower frequency.
    directory: "tools"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      tools:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # GitHub Actions doesn't support cooldown
  - package-ecosystem: "npm"
    directory: "docs"
    schedule:
      interval: "weekly"
    cooldown:
      # NPM churns a lot, but we don't need latest dependencies for serving docs.
      default-days: 7
    groups:
      docusaurus:
        patterns:
          - "*docusaurus*"
      react:
        patterns:
          - "*react*"
      eslint:
        patterns:
          - "*eslint*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    # Docker doesn't support cooldown
