# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      otel:
        patterns:
          - "go.opentelemetry.io/otel*"
          - "go.opentelemetry.io/contrib*"
          - "github.com/signalfx/splunk-otel-go*"
      buf:
        patterns:
          - "buf.build/*"
  - package-ecosystem: "gomod"
    directory: "tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "docs"
    schedule:
      interval: "weekly"
    groups:
      docusaurus:
        patterns:
          - "*docusaurus*"
      react:
        patterns:
          - "*react*"
      eslint:
        patterns:
          - "*eslint*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
