# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: minder-config
  labels:
    {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
data:
  server-config.yaml: |
    {{ .Files.Get "server-config.yaml.example" | nindent 4 }}
  overrides.yaml: |
    {{ .Values.extra_config | nindent 4}}
