# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: minder-http
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/api/v1/health"
  labels:
    {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: !!int "{{ .Values.service.httpPort }}"
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: minder

---

apiVersion: v1
kind: Service
metadata:
  name: minder-grpc
  annotations:
    alb.ingress.kubernetes.io/backend-protocol-version: "GRPC"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/minder.v1.HealthService/CheckHealth"
    # For some reason, ALB defaults to 12 (unimplemented) as a success code
    alb.ingress.kubernetes.io/success-codes: "0"
  labels:
    {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: !!int "{{ .Values.service.grpcPort }}"
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: minder

---

apiVersion: v1
kind: Service
metadata:
  name: minder-metrics
  labels:
  {{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: !!int "{{ .Values.service.metricPort }}"
      targetPort: http
      protocol: TCP
      name: metrics
  selector:
    app: minder
