// Copyright 2024 Stacklok, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package server

// CryptoConfig is the configuration for the crypto engine
type CryptoConfig struct {
	KeyStore KeyStoreConfig `mapstructure:"keystore"`
	Default  DefaultCrypto  `mapstructure:"default"`
	Fallback FallbackCrypto `mapstructure:"fallback"`
}

// KeyStoreConfig specifies the type of keystore to use and its configuration
// If we support multiple types of keystore (e.g. local, aws secrets, vault, etc.)
// it is intended that there will be one field for each type of keystore config,
// and that the `Type` field specifies which one to use
type KeyStoreConfig struct {
	Type  string              `mapstructure:"type" default:"local"`
	Local LocalKeyStoreConfig `mapstructure:"local"`
}

// DefaultCrypto defines the default crypto to be used for new data
type DefaultCrypto struct {
	// `token_key_passphrase` is the filename generated by `make bootstrap`
	KeyID     string `mapstructure:"key_id"`
	Algorithm string `mapstructure:"algorithm" default:"aes-256-gcm"`
}

// FallbackCrypto defines the optional key and algorithm which can be used for
// decrypting old secrets.
// This is used for rotating keys or algorithms.
type FallbackCrypto struct {
	KeyID     string `mapstructure:"key_id"`
	Algorithm string `mapstructure:"algorithm" default:"aes-256-cfb"`
}

// LocalKeyStoreConfig contains configuration for the local file keystore
type LocalKeyStoreConfig struct {
	// `./.ssh/` is the directory generated by `make bootstrap`
	KeyDir string `mapstructure:"key_dir" default:"./.ssh/"`
}
