// Code generated by MockGen. DO NOT EDIT.
// Source: ./auth_manager.go
//
// Generated by this command:
//
//	mockgen -package mock_manager -destination=./mock/auth_manager.go -source=./auth_manager.go
//

// Package mock_manager is a generated GoMock package.
package mock_manager

import (
	context "context"
	json "encoding/json"
	http "net/http"
	reflect "reflect"

	db "github.com/mindersec/minder/internal/db"
	v1 "github.com/mindersec/minder/pkg/providers/v1"
	manager "github.com/mindersec/minder/pkg/providers/v1/manager"
	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockproviderClassOAuthManager is a mock of providerClassOAuthManager interface.
type MockproviderClassOAuthManager struct {
	ctrl     *gomock.Controller
	recorder *MockproviderClassOAuthManagerMockRecorder
}

// MockproviderClassOAuthManagerMockRecorder is the mock recorder for MockproviderClassOAuthManager.
type MockproviderClassOAuthManagerMockRecorder struct {
	mock *MockproviderClassOAuthManager
}

// NewMockproviderClassOAuthManager creates a new mock instance.
func NewMockproviderClassOAuthManager(ctrl *gomock.Controller) *MockproviderClassOAuthManager {
	mock := &MockproviderClassOAuthManager{ctrl: ctrl}
	mock.recorder = &MockproviderClassOAuthManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproviderClassOAuthManager) EXPECT() *MockproviderClassOAuthManagerMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockproviderClassOAuthManager) Build(ctx context.Context, config *db.Provider) (v1.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, config)
	ret0, _ := ret[0].(v1.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockproviderClassOAuthManagerMockRecorder) Build(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).Build), ctx, config)
}

// Delete mocks base method.
func (m *MockproviderClassOAuthManager) Delete(ctx context.Context, config *db.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockproviderClassOAuthManagerMockRecorder) Delete(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).Delete), ctx, config)
}

// GetSupportedClasses mocks base method.
func (m *MockproviderClassOAuthManager) GetSupportedClasses() []db.ProviderClass {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupportedClasses")
	ret0, _ := ret[0].([]db.ProviderClass)
	return ret0
}

// GetSupportedClasses indicates an expected call of GetSupportedClasses.
func (mr *MockproviderClassOAuthManagerMockRecorder) GetSupportedClasses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupportedClasses", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).GetSupportedClasses))
}

// GetWebhookHandler mocks base method.
func (m *MockproviderClassOAuthManager) GetWebhookHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// GetWebhookHandler indicates an expected call of GetWebhookHandler.
func (mr *MockproviderClassOAuthManagerMockRecorder) GetWebhookHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookHandler", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).GetWebhookHandler))
}

// MarshallConfig mocks base method.
func (m *MockproviderClassOAuthManager) MarshallConfig(ctx context.Context, class db.ProviderClass, config json.RawMessage) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarshallConfig", ctx, class, config)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarshallConfig indicates an expected call of MarshallConfig.
func (mr *MockproviderClassOAuthManagerMockRecorder) MarshallConfig(ctx, class, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarshallConfig", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).MarshallConfig), ctx, class, config)
}

// NewOAuthConfig mocks base method.
func (m *MockproviderClassOAuthManager) NewOAuthConfig(providerClass string, cli bool) (*oauth2.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOAuthConfig", providerClass, cli)
	ret0, _ := ret[0].(*oauth2.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewOAuthConfig indicates an expected call of NewOAuthConfig.
func (mr *MockproviderClassOAuthManagerMockRecorder) NewOAuthConfig(providerClass, cli any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOAuthConfig", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).NewOAuthConfig), providerClass, cli)
}

// ValidateCredentials mocks base method.
func (m *MockproviderClassOAuthManager) ValidateCredentials(ctx context.Context, cred v1.Credential, params *manager.CredentialVerifyParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCredentials", ctx, cred, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCredentials indicates an expected call of ValidateCredentials.
func (mr *MockproviderClassOAuthManagerMockRecorder) ValidateCredentials(ctx, cred, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCredentials", reflect.TypeOf((*MockproviderClassOAuthManager)(nil).ValidateCredentials), ctx, cred, params)
}
