# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

contact_links:
  - name: Ask the community
    url: https://discord.com/invite/RkzVuTp3WK
    about: Ask and discuss questions with other Minder community members on Discord.
