name: Feature request
description: Suggest new or updated features to include in Minder.
title: "Suggest a new feature"
labels: [feature-request]
assignees: "-"
body:
  - type: textarea
    id: description
    attributes:
      label: Please describe the enhancement
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...], this could be improved by [...], this would provide the ability to [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution Proposal
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: considerations
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here. e.g. link to a Google doc if the design is being discussed there.
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What does done look like?
