branches:
  - name: main
    rules:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      allow_fork_syncing: true
  - name: master
    rules:
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      allow_fork_syncing: true
