# SPDX-FileCopyrightText: Copyright 2024 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

# This configuration defines the endpoints for the minder CLI when
# communicating with a local Minder instance.
#
# Set MINDER_CONFIG to point to this file to communicate with Minder
# running locally.

grpc_server:
  host: localhost
  port: 8090
  insecure: true

identity:
  cli:
    issuer_url: http://localhost:8081
    client_id: minder-cli
