# SPDX-FileCopyrightText: Copyright 2024 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

# This configuration defines the endpoints for the minder CLI when
# communicating with the staging version of the Stacklok Minder instance.
# Note that the staging instance may have high instability and rollbacks
# or data loss.
#
# Set MINDER_CONFIG to point to this file to communicate with the
# staging Minder instance.

grpc_server:
  host: staging.stacklok.dev
  port: 443
  insecure: false

identity:
  cli:
    issuer_url: https://auth.staging.stacklok.dev
    client_id: minder-cli
