# SPDX-FileCopyrightText: Copyright 2024 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

# This configuration defines the endpoints for the minder CLI when
# communicating with the Stacklok Minder instance.
#
# Set MINDER_CONFIG to point to this file to communicate with the
# hosted Minder instance.

grpc_server:
  host: api.stacklok.com
  port: 443
  insecure: false

identity:
  cli:
    issuer_url: https://auth.stacklok.com
    client_id: minder-cli
