// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1 (interfaces: ProjectsServiceClient)
//
// Generated by this command:
//
//	mockgen -package mock_minderv1 -destination pkg/api/protobuf/go/minder/v1/mock/projects_client_mock.go github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1 ProjectsServiceClient
//

// Package mock_minderv1 is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockProjectsServiceClient is a mock of ProjectsServiceClient interface.
type MockProjectsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockProjectsServiceClientMockRecorder
	isgomock struct{}
}

// MockProjectsServiceClientMockRecorder is the mock recorder for MockProjectsServiceClient.
type MockProjectsServiceClientMockRecorder struct {
	mock *MockProjectsServiceClient
}

// NewMockProjectsServiceClient creates a new mock instance.
func NewMockProjectsServiceClient(ctrl *gomock.Controller) *MockProjectsServiceClient {
	mock := &MockProjectsServiceClient{ctrl: ctrl}
	mock.recorder = &MockProjectsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectsServiceClient) EXPECT() *MockProjectsServiceClientMockRecorder {
	return m.recorder
}

// CreateEntityReconciliationTask mocks base method.
func (m *MockProjectsServiceClient) CreateEntityReconciliationTask(ctx context.Context, in *v1.CreateEntityReconciliationTaskRequest, opts ...grpc.CallOption) (*v1.CreateEntityReconciliationTaskResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateEntityReconciliationTask", varargs...)
	ret0, _ := ret[0].(*v1.CreateEntityReconciliationTaskResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntityReconciliationTask indicates an expected call of CreateEntityReconciliationTask.
func (mr *MockProjectsServiceClientMockRecorder) CreateEntityReconciliationTask(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntityReconciliationTask", reflect.TypeOf((*MockProjectsServiceClient)(nil).CreateEntityReconciliationTask), varargs...)
}

// CreateProject mocks base method.
func (m *MockProjectsServiceClient) CreateProject(ctx context.Context, in *v1.CreateProjectRequest, opts ...grpc.CallOption) (*v1.CreateProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProject", varargs...)
	ret0, _ := ret[0].(*v1.CreateProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockProjectsServiceClientMockRecorder) CreateProject(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockProjectsServiceClient)(nil).CreateProject), varargs...)
}

// DeleteProject mocks base method.
func (m *MockProjectsServiceClient) DeleteProject(ctx context.Context, in *v1.DeleteProjectRequest, opts ...grpc.CallOption) (*v1.DeleteProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteProject", varargs...)
	ret0, _ := ret[0].(*v1.DeleteProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockProjectsServiceClientMockRecorder) DeleteProject(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockProjectsServiceClient)(nil).DeleteProject), varargs...)
}

// ListChildProjects mocks base method.
func (m *MockProjectsServiceClient) ListChildProjects(ctx context.Context, in *v1.ListChildProjectsRequest, opts ...grpc.CallOption) (*v1.ListChildProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListChildProjects", varargs...)
	ret0, _ := ret[0].(*v1.ListChildProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChildProjects indicates an expected call of ListChildProjects.
func (mr *MockProjectsServiceClientMockRecorder) ListChildProjects(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChildProjects", reflect.TypeOf((*MockProjectsServiceClient)(nil).ListChildProjects), varargs...)
}

// ListProjects mocks base method.
func (m *MockProjectsServiceClient) ListProjects(ctx context.Context, in *v1.ListProjectsRequest, opts ...grpc.CallOption) (*v1.ListProjectsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProjects", varargs...)
	ret0, _ := ret[0].(*v1.ListProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectsServiceClientMockRecorder) ListProjects(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjectsServiceClient)(nil).ListProjects), varargs...)
}

// PatchProject mocks base method.
func (m *MockProjectsServiceClient) PatchProject(ctx context.Context, in *v1.PatchProjectRequest, opts ...grpc.CallOption) (*v1.PatchProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PatchProject", varargs...)
	ret0, _ := ret[0].(*v1.PatchProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchProject indicates an expected call of PatchProject.
func (mr *MockProjectsServiceClientMockRecorder) PatchProject(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchProject", reflect.TypeOf((*MockProjectsServiceClient)(nil).PatchProject), varargs...)
}

// UpdateProject mocks base method.
func (m *MockProjectsServiceClient) UpdateProject(ctx context.Context, in *v1.UpdateProjectRequest, opts ...grpc.CallOption) (*v1.UpdateProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProject", varargs...)
	ret0, _ := ret[0].(*v1.UpdateProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockProjectsServiceClientMockRecorder) UpdateProject(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockProjectsServiceClient)(nil).UpdateProject), varargs...)
}
