// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1 (interfaces: RepositoryServiceClient)
//
// Generated by this command:
//
//	mockgen -package mock_minderv1 -destination pkg/api/protobuf/go/minder/v1/mock/mock_repo.go github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1 RepositoryServiceClient
//

// Package mock_minderv1 is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRepositoryServiceClient is a mock of RepositoryServiceClient interface.
type MockRepositoryServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryServiceClientMockRecorder
	isgomock struct{}
}

// MockRepositoryServiceClientMockRecorder is the mock recorder for MockRepositoryServiceClient.
type MockRepositoryServiceClientMockRecorder struct {
	mock *MockRepositoryServiceClient
}

// NewMockRepositoryServiceClient creates a new mock instance.
func NewMockRepositoryServiceClient(ctrl *gomock.Controller) *MockRepositoryServiceClient {
	mock := &MockRepositoryServiceClient{ctrl: ctrl}
	mock.recorder = &MockRepositoryServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryServiceClient) EXPECT() *MockRepositoryServiceClientMockRecorder {
	return m.recorder
}

// DeleteRepositoryById mocks base method.
func (m *MockRepositoryServiceClient) DeleteRepositoryById(ctx context.Context, in *v1.DeleteRepositoryByIdRequest, opts ...grpc.CallOption) (*v1.DeleteRepositoryByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRepositoryById", varargs...)
	ret0, _ := ret[0].(*v1.DeleteRepositoryByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRepositoryById indicates an expected call of DeleteRepositoryById.
func (mr *MockRepositoryServiceClientMockRecorder) DeleteRepositoryById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepositoryById", reflect.TypeOf((*MockRepositoryServiceClient)(nil).DeleteRepositoryById), varargs...)
}

// DeleteRepositoryByName mocks base method.
func (m *MockRepositoryServiceClient) DeleteRepositoryByName(ctx context.Context, in *v1.DeleteRepositoryByNameRequest, opts ...grpc.CallOption) (*v1.DeleteRepositoryByNameResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteRepositoryByName", varargs...)
	ret0, _ := ret[0].(*v1.DeleteRepositoryByNameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteRepositoryByName indicates an expected call of DeleteRepositoryByName.
func (mr *MockRepositoryServiceClientMockRecorder) DeleteRepositoryByName(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRepositoryByName", reflect.TypeOf((*MockRepositoryServiceClient)(nil).DeleteRepositoryByName), varargs...)
}

// GetRepositoryById mocks base method.
func (m *MockRepositoryServiceClient) GetRepositoryById(ctx context.Context, in *v1.GetRepositoryByIdRequest, opts ...grpc.CallOption) (*v1.GetRepositoryByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRepositoryById", varargs...)
	ret0, _ := ret[0].(*v1.GetRepositoryByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryById indicates an expected call of GetRepositoryById.
func (mr *MockRepositoryServiceClientMockRecorder) GetRepositoryById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryById", reflect.TypeOf((*MockRepositoryServiceClient)(nil).GetRepositoryById), varargs...)
}

// GetRepositoryByName mocks base method.
func (m *MockRepositoryServiceClient) GetRepositoryByName(ctx context.Context, in *v1.GetRepositoryByNameRequest, opts ...grpc.CallOption) (*v1.GetRepositoryByNameResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRepositoryByName", varargs...)
	ret0, _ := ret[0].(*v1.GetRepositoryByNameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepositoryByName indicates an expected call of GetRepositoryByName.
func (mr *MockRepositoryServiceClientMockRecorder) GetRepositoryByName(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepositoryByName", reflect.TypeOf((*MockRepositoryServiceClient)(nil).GetRepositoryByName), varargs...)
}

// ListRemoteRepositoriesFromProvider mocks base method.
func (m *MockRepositoryServiceClient) ListRemoteRepositoriesFromProvider(ctx context.Context, in *v1.ListRemoteRepositoriesFromProviderRequest, opts ...grpc.CallOption) (*v1.ListRemoteRepositoriesFromProviderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRemoteRepositoriesFromProvider", varargs...)
	ret0, _ := ret[0].(*v1.ListRemoteRepositoriesFromProviderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemoteRepositoriesFromProvider indicates an expected call of ListRemoteRepositoriesFromProvider.
func (mr *MockRepositoryServiceClientMockRecorder) ListRemoteRepositoriesFromProvider(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemoteRepositoriesFromProvider", reflect.TypeOf((*MockRepositoryServiceClient)(nil).ListRemoteRepositoriesFromProvider), varargs...)
}

// ListRepositories mocks base method.
func (m *MockRepositoryServiceClient) ListRepositories(ctx context.Context, in *v1.ListRepositoriesRequest, opts ...grpc.CallOption) (*v1.ListRepositoriesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListRepositories", varargs...)
	ret0, _ := ret[0].(*v1.ListRepositoriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockRepositoryServiceClientMockRecorder) ListRepositories(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockRepositoryServiceClient)(nil).ListRepositories), varargs...)
}

// RegisterRepository mocks base method.
func (m *MockRepositoryServiceClient) RegisterRepository(ctx context.Context, in *v1.RegisterRepositoryRequest, opts ...grpc.CallOption) (*v1.RegisterRepositoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterRepository", varargs...)
	ret0, _ := ret[0].(*v1.RegisterRepositoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterRepository indicates an expected call of RegisterRepository.
func (mr *MockRepositoryServiceClientMockRecorder) RegisterRepository(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRepository", reflect.TypeOf((*MockRepositoryServiceClient)(nil).RegisterRepository), varargs...)
}
