// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1 (interfaces: DataSourceServiceClient)
//
// Generated by this command:
//
//	mockgen -package mock -destination pkg/api/protobuf/go/minder/v1/mock/mock_datasource.go github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1 DataSourceServiceClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockDataSourceServiceClient is a mock of DataSourceServiceClient interface.
type MockDataSourceServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceServiceClientMockRecorder
	isgomock struct{}
}

// MockDataSourceServiceClientMockRecorder is the mock recorder for MockDataSourceServiceClient.
type MockDataSourceServiceClientMockRecorder struct {
	mock *MockDataSourceServiceClient
}

// NewMockDataSourceServiceClient creates a new mock instance.
func NewMockDataSourceServiceClient(ctrl *gomock.Controller) *MockDataSourceServiceClient {
	mock := &MockDataSourceServiceClient{ctrl: ctrl}
	mock.recorder = &MockDataSourceServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSourceServiceClient) EXPECT() *MockDataSourceServiceClientMockRecorder {
	return m.recorder
}

// CreateDataSource mocks base method.
func (m *MockDataSourceServiceClient) CreateDataSource(ctx context.Context, in *v1.CreateDataSourceRequest, opts ...grpc.CallOption) (*v1.CreateDataSourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDataSource", varargs...)
	ret0, _ := ret[0].(*v1.CreateDataSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDataSource indicates an expected call of CreateDataSource.
func (mr *MockDataSourceServiceClientMockRecorder) CreateDataSource(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDataSource", reflect.TypeOf((*MockDataSourceServiceClient)(nil).CreateDataSource), varargs...)
}

// DeleteDataSourceById mocks base method.
func (m *MockDataSourceServiceClient) DeleteDataSourceById(ctx context.Context, in *v1.DeleteDataSourceByIdRequest, opts ...grpc.CallOption) (*v1.DeleteDataSourceByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDataSourceById", varargs...)
	ret0, _ := ret[0].(*v1.DeleteDataSourceByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDataSourceById indicates an expected call of DeleteDataSourceById.
func (mr *MockDataSourceServiceClientMockRecorder) DeleteDataSourceById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataSourceById", reflect.TypeOf((*MockDataSourceServiceClient)(nil).DeleteDataSourceById), varargs...)
}

// DeleteDataSourceByName mocks base method.
func (m *MockDataSourceServiceClient) DeleteDataSourceByName(ctx context.Context, in *v1.DeleteDataSourceByNameRequest, opts ...grpc.CallOption) (*v1.DeleteDataSourceByNameResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDataSourceByName", varargs...)
	ret0, _ := ret[0].(*v1.DeleteDataSourceByNameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDataSourceByName indicates an expected call of DeleteDataSourceByName.
func (mr *MockDataSourceServiceClientMockRecorder) DeleteDataSourceByName(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDataSourceByName", reflect.TypeOf((*MockDataSourceServiceClient)(nil).DeleteDataSourceByName), varargs...)
}

// GetDataSourceById mocks base method.
func (m *MockDataSourceServiceClient) GetDataSourceById(ctx context.Context, in *v1.GetDataSourceByIdRequest, opts ...grpc.CallOption) (*v1.GetDataSourceByIdResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDataSourceById", varargs...)
	ret0, _ := ret[0].(*v1.GetDataSourceByIdResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataSourceById indicates an expected call of GetDataSourceById.
func (mr *MockDataSourceServiceClientMockRecorder) GetDataSourceById(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataSourceById", reflect.TypeOf((*MockDataSourceServiceClient)(nil).GetDataSourceById), varargs...)
}

// GetDataSourceByName mocks base method.
func (m *MockDataSourceServiceClient) GetDataSourceByName(ctx context.Context, in *v1.GetDataSourceByNameRequest, opts ...grpc.CallOption) (*v1.GetDataSourceByNameResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDataSourceByName", varargs...)
	ret0, _ := ret[0].(*v1.GetDataSourceByNameResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataSourceByName indicates an expected call of GetDataSourceByName.
func (mr *MockDataSourceServiceClientMockRecorder) GetDataSourceByName(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataSourceByName", reflect.TypeOf((*MockDataSourceServiceClient)(nil).GetDataSourceByName), varargs...)
}

// ListDataSources mocks base method.
func (m *MockDataSourceServiceClient) ListDataSources(ctx context.Context, in *v1.ListDataSourcesRequest, opts ...grpc.CallOption) (*v1.ListDataSourcesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDataSources", varargs...)
	ret0, _ := ret[0].(*v1.ListDataSourcesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDataSources indicates an expected call of ListDataSources.
func (mr *MockDataSourceServiceClientMockRecorder) ListDataSources(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDataSources", reflect.TypeOf((*MockDataSourceServiceClient)(nil).ListDataSources), varargs...)
}

// UpdateDataSource mocks base method.
func (m *MockDataSourceServiceClient) UpdateDataSource(ctx context.Context, in *v1.UpdateDataSourceRequest, opts ...grpc.CallOption) (*v1.UpdateDataSourceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateDataSource", varargs...)
	ret0, _ := ret[0].(*v1.UpdateDataSourceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDataSource indicates an expected call of UpdateDataSource.
func (mr *MockDataSourceServiceClientMockRecorder) UpdateDataSource(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDataSource", reflect.TypeOf((*MockDataSourceServiceClient)(nil).UpdateDataSource), varargs...)
}
