//
// Copyright 2023 Stacklok, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: minder/v1alpha/minder.proto

package v1alpha

import (
	v1 "github.com/stacklok/minder/pkg/api/protobuf/go/minder/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListEvaluationResultsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// context is the context in which the evaluation results are evaluated.
	Context  *v1.Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	NewField string      `protobuf:"bytes,6,opt,name=new_field,json=newField,proto3" json:"new_field,omitempty"`
	// profile is the profile name or ID to retrieve results for.
	// If empty, return evaluation results for profiles selected by
	// an empty label_filter.
	//
	// Types that are assignable to ProfileSelector:
	//
	//	*ListEvaluationResultsRequest_Profile
	//	*ListEvaluationResultsRequest_LabelFilter
	ProfileSelector isListEvaluationResultsRequest_ProfileSelector `protobuf_oneof:"profile_selector"`
	// If set, only return evaluation results for the named entities.
	// If empty, return evaluation results for all entities
	Entity []*v1.EntityTypedId `protobuf:"bytes,4,rep,name=entity,proto3" json:"entity,omitempty"`
	// If set, only return evaluation results for the named rules.
	// If empty, return evaluation results for all rules
	RuleName []string `protobuf:"bytes,5,rep,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
}

func (x *ListEvaluationResultsRequest) Reset() {
	*x = ListEvaluationResultsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEvaluationResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvaluationResultsRequest) ProtoMessage() {}

func (x *ListEvaluationResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvaluationResultsRequest.ProtoReflect.Descriptor instead.
func (*ListEvaluationResultsRequest) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{0}
}

func (x *ListEvaluationResultsRequest) GetContext() *v1.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListEvaluationResultsRequest) GetNewField() string {
	if x != nil {
		return x.NewField
	}
	return ""
}

func (m *ListEvaluationResultsRequest) GetProfileSelector() isListEvaluationResultsRequest_ProfileSelector {
	if m != nil {
		return m.ProfileSelector
	}
	return nil
}

func (x *ListEvaluationResultsRequest) GetProfile() string {
	if x, ok := x.GetProfileSelector().(*ListEvaluationResultsRequest_Profile); ok {
		return x.Profile
	}
	return ""
}

func (x *ListEvaluationResultsRequest) GetLabelFilter() string {
	if x, ok := x.GetProfileSelector().(*ListEvaluationResultsRequest_LabelFilter); ok {
		return x.LabelFilter
	}
	return ""
}

func (x *ListEvaluationResultsRequest) GetEntity() []*v1.EntityTypedId {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *ListEvaluationResultsRequest) GetRuleName() []string {
	if x != nil {
		return x.RuleName
	}
	return nil
}

type isListEvaluationResultsRequest_ProfileSelector interface {
	isListEvaluationResultsRequest_ProfileSelector()
}

type ListEvaluationResultsRequest_Profile struct {
	// ID can contain either a profile name or an ID
	Profile string `protobuf:"bytes,2,opt,name=profile,proto3,oneof"`
}

type ListEvaluationResultsRequest_LabelFilter struct {
	// Filter profiles to only those matching the specified labels.
	//
	// The default is to return all user-created profiles; the string "*" can
	// be used to select all profiles, including system profiles.  This syntax
	// may be expanded in the future.
	LabelFilter string `protobuf:"bytes,3,opt,name=label_filter,json=labelFilter,proto3,oneof"`
}

func (*ListEvaluationResultsRequest_Profile) isListEvaluationResultsRequest_ProfileSelector() {}

func (*ListEvaluationResultsRequest_LabelFilter) isListEvaluationResultsRequest_ProfileSelector() {}

type ListEvaluationResultsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Each entity selected by the list request will have _single_ entry in entities which contains results of all evaluations for each profile.
	Entities []*ListEvaluationResultsResponse_EntityEvaluationResults `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *ListEvaluationResultsResponse) Reset() {
	*x = ListEvaluationResultsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEvaluationResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvaluationResultsResponse) ProtoMessage() {}

func (x *ListEvaluationResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvaluationResultsResponse.ProtoReflect.Descriptor instead.
func (*ListEvaluationResultsResponse) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{1}
}

func (x *ListEvaluationResultsResponse) GetEntities() []*ListEvaluationResultsResponse_EntityEvaluationResults {
	if x != nil {
		return x.Entities
	}
	return nil
}

// ListEvaluationHistoryRequest represents a request message for the
// ListEvaluationHistory RPC.
//
// Most of its fields are used for filtering, except for `cursor`
// which is used for pagination.
type ListEvaluationHistoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Context *v1.Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// List of entity types to retrieve.
	EntityType []string `protobuf:"bytes,2,rep,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	// List of entity names to retrieve.
	EntityName []string `protobuf:"bytes,3,rep,name=entity_name,json=entityName,proto3" json:"entity_name,omitempty"`
	// List of profile names to retrieve.
	ProfileName []string `protobuf:"bytes,4,rep,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	// List of evaluation statuses to retrieve.
	Status []string `protobuf:"bytes,5,rep,name=status,proto3" json:"status,omitempty"`
	// List of remediation statuses to retrieve.
	Remediation []string `protobuf:"bytes,6,rep,name=remediation,proto3" json:"remediation,omitempty"`
	// List of alert statuses to retrieve.
	Alert []string `protobuf:"bytes,7,rep,name=alert,proto3" json:"alert,omitempty"`
	// Timestamp representing the start time of the selection window.
	From *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=from,proto3" json:"from,omitempty"`
	// Timestamp representing the end time of the selection window.
	To *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=to,proto3" json:"to,omitempty"`
	// Cursor object to select the "page" of data to retrieve.
	Cursor *v1.Cursor `protobuf:"bytes,10,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *ListEvaluationHistoryRequest) Reset() {
	*x = ListEvaluationHistoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEvaluationHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvaluationHistoryRequest) ProtoMessage() {}

func (x *ListEvaluationHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvaluationHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListEvaluationHistoryRequest) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{2}
}

func (x *ListEvaluationHistoryRequest) GetContext() *v1.Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetEntityType() []string {
	if x != nil {
		return x.EntityType
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetEntityName() []string {
	if x != nil {
		return x.EntityName
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetProfileName() []string {
	if x != nil {
		return x.ProfileName
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetStatus() []string {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetRemediation() []string {
	if x != nil {
		return x.Remediation
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetAlert() []string {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListEvaluationHistoryRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

// ListEvaluationHistoryResponse represents a response message for the
// ListEvaluationHistory RPC.
//
// It ships a collection of records retrieved and pointers to get to
// the next and/or previous pages of data.
type ListEvaluationHistoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of records retrieved.
	Data []*EvaluationHistory `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// Metadata of the current page and pointers to next and/or
	// previous pages.
	Page *v1.CursorPage `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListEvaluationHistoryResponse) Reset() {
	*x = ListEvaluationHistoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEvaluationHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvaluationHistoryResponse) ProtoMessage() {}

func (x *ListEvaluationHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvaluationHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListEvaluationHistoryResponse) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{3}
}

func (x *ListEvaluationHistoryResponse) GetData() []*EvaluationHistory {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListEvaluationHistoryResponse) GetPage() *v1.CursorPage {
	if x != nil {
		return x.Page
	}
	return nil
}

type EvaluationHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// entity contains details of the entity which was evaluated.
	Entity *EvaluationHistoryEntity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// rule contains details of the rule which the entity was evaluated against.
	Rule *EvaluationHistoryRule `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	// status contains the evaluation status.
	Status *EvaluationHistoryStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// alert contains details of the alerts for this evaluation.
	Alert *EvaluationHistoryAlert `protobuf:"bytes,4,opt,name=alert,proto3" json:"alert,omitempty"`
	// remediation contains details of the remediation for this evaluation.
	Remediation *EvaluationHistoryRemediation `protobuf:"bytes,5,opt,name=remediation,proto3" json:"remediation,omitempty"`
}

func (x *EvaluationHistory) Reset() {
	*x = EvaluationHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationHistory) ProtoMessage() {}

func (x *EvaluationHistory) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationHistory.ProtoReflect.Descriptor instead.
func (*EvaluationHistory) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluationHistory) GetEntity() *EvaluationHistoryEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EvaluationHistory) GetRule() *EvaluationHistoryRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *EvaluationHistory) GetStatus() *EvaluationHistoryStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EvaluationHistory) GetAlert() *EvaluationHistoryAlert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *EvaluationHistory) GetRemediation() *EvaluationHistoryRemediation {
	if x != nil {
		return x.Remediation
	}
	return nil
}

type EvaluationHistoryEntity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is the ID of the entity.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is the entity type.
	Type v1.Entity `protobuf:"varint,2,opt,name=type,proto3,enum=minder.v1.Entity" json:"type,omitempty"`
	// name is the entity name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EvaluationHistoryEntity) Reset() {
	*x = EvaluationHistoryEntity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationHistoryEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationHistoryEntity) ProtoMessage() {}

func (x *EvaluationHistoryEntity) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationHistoryEntity.ProtoReflect.Descriptor instead.
func (*EvaluationHistoryEntity) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{5}
}

func (x *EvaluationHistoryEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EvaluationHistoryEntity) GetType() v1.Entity {
	if x != nil {
		return x.Type
	}
	return v1.Entity(0)
}

func (x *EvaluationHistoryEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EvaluationHistoryRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the name of the rule instance.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is the name of the rule type.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// profile is the name of the profile which contains the rule.
	Profile string `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *EvaluationHistoryRule) Reset() {
	*x = EvaluationHistoryRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationHistoryRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationHistoryRule) ProtoMessage() {}

func (x *EvaluationHistoryRule) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationHistoryRule.ProtoReflect.Descriptor instead.
func (*EvaluationHistoryRule) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{6}
}

func (x *EvaluationHistoryRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EvaluationHistoryRule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EvaluationHistoryRule) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type EvaluationHistoryStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status is one of (success, error, failure, skipped)
	// not using enums to mirror the behaviour of the existing API contracts.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// details contains optional details about the evaluation.
	// the structure and contents are rule type specific, and are subject to change.
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *EvaluationHistoryStatus) Reset() {
	*x = EvaluationHistoryStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationHistoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationHistoryStatus) ProtoMessage() {}

func (x *EvaluationHistoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationHistoryStatus.ProtoReflect.Descriptor instead.
func (*EvaluationHistoryStatus) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{7}
}

func (x *EvaluationHistoryStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvaluationHistoryStatus) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type EvaluationHistoryRemediation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status is one of (success, error, failure, skipped, not available)
	// not using enums to mirror the behaviour of the existing API contracts.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// details contains optional details about the remediation.
	// the structure and contents are remediation specific, and are subject to change.
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *EvaluationHistoryRemediation) Reset() {
	*x = EvaluationHistoryRemediation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationHistoryRemediation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationHistoryRemediation) ProtoMessage() {}

func (x *EvaluationHistoryRemediation) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationHistoryRemediation.ProtoReflect.Descriptor instead.
func (*EvaluationHistoryRemediation) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluationHistoryRemediation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvaluationHistoryRemediation) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type EvaluationHistoryAlert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// status is one of (on, off, error, skipped, not available)
	// not using enums to mirror the behaviour of the existing API contracts.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// details contains optional details about the alert.
	// the structure and contents are alert specific, and are subject to change.
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *EvaluationHistoryAlert) Reset() {
	*x = EvaluationHistoryAlert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluationHistoryAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationHistoryAlert) ProtoMessage() {}

func (x *EvaluationHistoryAlert) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationHistoryAlert.ProtoReflect.Descriptor instead.
func (*EvaluationHistoryAlert) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluationHistoryAlert) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvaluationHistoryAlert) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type ListEvaluationResultsResponse_EntityProfileEvaluationResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// profile_status is the status of the profile - id, name, status, last_updated
	ProfileStatus *v1.ProfileStatus `protobuf:"bytes,1,opt,name=profile_status,json=profileStatus,proto3" json:"profile_status,omitempty"`
	// Note that some fields like profile_id and entity might be empty
	// Eventually we might replace this type with another one that fits the API better
	Results []*v1.RuleEvaluationStatus `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ListEvaluationResultsResponse_EntityProfileEvaluationResults) Reset() {
	*x = ListEvaluationResultsResponse_EntityProfileEvaluationResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEvaluationResultsResponse_EntityProfileEvaluationResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvaluationResultsResponse_EntityProfileEvaluationResults) ProtoMessage() {}

func (x *ListEvaluationResultsResponse_EntityProfileEvaluationResults) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvaluationResultsResponse_EntityProfileEvaluationResults.ProtoReflect.Descriptor instead.
func (*ListEvaluationResultsResponse_EntityProfileEvaluationResults) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListEvaluationResultsResponse_EntityProfileEvaluationResults) GetProfileStatus() *v1.ProfileStatus {
	if x != nil {
		return x.ProfileStatus
	}
	return nil
}

func (x *ListEvaluationResultsResponse_EntityProfileEvaluationResults) GetResults() []*v1.RuleEvaluationStatus {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListEvaluationResultsResponse_EntityEvaluationResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity   *v1.EntityTypedId                                               `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	Profiles []*ListEvaluationResultsResponse_EntityProfileEvaluationResults `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
}

func (x *ListEvaluationResultsResponse_EntityEvaluationResults) Reset() {
	*x = ListEvaluationResultsResponse_EntityEvaluationResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minder_v1alpha_minder_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListEvaluationResultsResponse_EntityEvaluationResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEvaluationResultsResponse_EntityEvaluationResults) ProtoMessage() {}

func (x *ListEvaluationResultsResponse_EntityEvaluationResults) ProtoReflect() protoreflect.Message {
	mi := &file_minder_v1alpha_minder_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEvaluationResultsResponse_EntityEvaluationResults.ProtoReflect.Descriptor instead.
func (*ListEvaluationResultsResponse_EntityEvaluationResults) Descriptor() ([]byte, []int) {
	return file_minder_v1alpha_minder_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListEvaluationResultsResponse_EntityEvaluationResults) GetEntity() *v1.EntityTypedId {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *ListEvaluationResultsResponse_EntityEvaluationResults) GetProfiles() []*ListEvaluationResultsResponse_EntityProfileEvaluationResults {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var file_minder_v1alpha_minder_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*v1.RpcOptions)(nil),
		Field:         51078,
		Name:          "minder.v1alpha.rpc_options",
		Tag:           "bytes,51078,opt,name=rpc_options",
		Filename:      "minder/v1alpha/minder.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional minder.v1.RpcOptions rpc_options = 51078;
	E_RpcOptions = &file_minder_v1alpha_minder_proto_extTypes[0]
)

var File_minder_v1alpha_minder_proto protoreflect.FileDescriptor

var file_minder_v1alpha_minder_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x2f, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6d,
	0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x02, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x1a, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x23,
	0x0a, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x64, 0x49, 0x64, 0x52, 0x06, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x42, 0x12, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xe7, 0x03, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x1a, 0x9c, 0x01, 0x0a, 0x1e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x3f,
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x39, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c,
	0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xb5, 0x01, 0x0a, 0x17, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x64, 0x49, 0x64,
	0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x68, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x4c, 0x2e, 0x6d, 0x69, 0x6e,
	0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x4a, 0x04, 0x08, 0x01, 0x10, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x88, 0x03, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x0b,
	0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x61,
	0x6c, 0x65, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x29, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x81, 0x01, 0x0a, 0x1d,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22,
	0xde, 0x02, 0x0a, 0x11, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x3f, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x75, 0x6c,
	0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x3c, 0x0a, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x26, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x05, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x12, 0x4e, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x64, 0x0a, 0x17, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x15, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x75, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x22, 0x4b, 0x0a, 0x17, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x50,
	0x0a, 0x1c, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x22, 0x4a, 0x0a, 0x16, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x32, 0xc9, 0x02, 0x0a,
	0x12, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x95, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x2c, 0x2e,
	0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6d, 0x69,
	0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0xb2, 0xf8, 0x18, 0x04,
	0x30, 0x03, 0x38, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x9a, 0x01, 0x0a, 0x15,
	0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2c, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x24, 0xaa, 0xf8, 0x18, 0x04, 0x30, 0x03, 0x38, 0x21, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x16, 0x12, 0x14, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x2f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x3a, 0x58, 0x0a, 0x0b, 0x72, 0x70, 0x63, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x86, 0x8f, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x70, 0x63, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0a, 0x72, 0x70, 0x63, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x6c, 0x6f, 0x6b, 0x2f, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x69, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_minder_v1alpha_minder_proto_rawDescOnce sync.Once
	file_minder_v1alpha_minder_proto_rawDescData = file_minder_v1alpha_minder_proto_rawDesc
)

func file_minder_v1alpha_minder_proto_rawDescGZIP() []byte {
	file_minder_v1alpha_minder_proto_rawDescOnce.Do(func() {
		file_minder_v1alpha_minder_proto_rawDescData = protoimpl.X.CompressGZIP(file_minder_v1alpha_minder_proto_rawDescData)
	})
	return file_minder_v1alpha_minder_proto_rawDescData
}

var file_minder_v1alpha_minder_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_minder_v1alpha_minder_proto_goTypes = []any{
	(*ListEvaluationResultsRequest)(nil),                                 // 0: minder.v1alpha.ListEvaluationResultsRequest
	(*ListEvaluationResultsResponse)(nil),                                // 1: minder.v1alpha.ListEvaluationResultsResponse
	(*ListEvaluationHistoryRequest)(nil),                                 // 2: minder.v1alpha.ListEvaluationHistoryRequest
	(*ListEvaluationHistoryResponse)(nil),                                // 3: minder.v1alpha.ListEvaluationHistoryResponse
	(*EvaluationHistory)(nil),                                            // 4: minder.v1alpha.EvaluationHistory
	(*EvaluationHistoryEntity)(nil),                                      // 5: minder.v1alpha.EvaluationHistoryEntity
	(*EvaluationHistoryRule)(nil),                                        // 6: minder.v1alpha.EvaluationHistoryRule
	(*EvaluationHistoryStatus)(nil),                                      // 7: minder.v1alpha.EvaluationHistoryStatus
	(*EvaluationHistoryRemediation)(nil),                                 // 8: minder.v1alpha.EvaluationHistoryRemediation
	(*EvaluationHistoryAlert)(nil),                                       // 9: minder.v1alpha.EvaluationHistoryAlert
	(*ListEvaluationResultsResponse_EntityProfileEvaluationResults)(nil), // 10: minder.v1alpha.ListEvaluationResultsResponse.EntityProfileEvaluationResults
	(*ListEvaluationResultsResponse_EntityEvaluationResults)(nil),        // 11: minder.v1alpha.ListEvaluationResultsResponse.EntityEvaluationResults
	(*v1.Context)(nil),                                                   // 12: minder.v1.Context
	(*v1.EntityTypedId)(nil),                                             // 13: minder.v1.EntityTypedId
	(*timestamppb.Timestamp)(nil),                                        // 14: google.protobuf.Timestamp
	(*v1.Cursor)(nil),                                                    // 15: minder.v1.Cursor
	(*v1.CursorPage)(nil),                                                // 16: minder.v1.CursorPage
	(v1.Entity)(0),                                                       // 17: minder.v1.Entity
	(*v1.ProfileStatus)(nil),                                             // 18: minder.v1.ProfileStatus
	(*v1.RuleEvaluationStatus)(nil),                                      // 19: minder.v1.RuleEvaluationStatus
	(*descriptorpb.MethodOptions)(nil),                                   // 20: google.protobuf.MethodOptions
	(*v1.RpcOptions)(nil),                                                // 21: minder.v1.RpcOptions
}
var file_minder_v1alpha_minder_proto_depIdxs = []int32{
	12, // 0: minder.v1alpha.ListEvaluationResultsRequest.context:type_name -> minder.v1.Context
	13, // 1: minder.v1alpha.ListEvaluationResultsRequest.entity:type_name -> minder.v1.EntityTypedId
	11, // 2: minder.v1alpha.ListEvaluationResultsResponse.entities:type_name -> minder.v1alpha.ListEvaluationResultsResponse.EntityEvaluationResults
	12, // 3: minder.v1alpha.ListEvaluationHistoryRequest.context:type_name -> minder.v1.Context
	14, // 4: minder.v1alpha.ListEvaluationHistoryRequest.from:type_name -> google.protobuf.Timestamp
	14, // 5: minder.v1alpha.ListEvaluationHistoryRequest.to:type_name -> google.protobuf.Timestamp
	15, // 6: minder.v1alpha.ListEvaluationHistoryRequest.cursor:type_name -> minder.v1.Cursor
	4,  // 7: minder.v1alpha.ListEvaluationHistoryResponse.data:type_name -> minder.v1alpha.EvaluationHistory
	16, // 8: minder.v1alpha.ListEvaluationHistoryResponse.page:type_name -> minder.v1.CursorPage
	5,  // 9: minder.v1alpha.EvaluationHistory.entity:type_name -> minder.v1alpha.EvaluationHistoryEntity
	6,  // 10: minder.v1alpha.EvaluationHistory.rule:type_name -> minder.v1alpha.EvaluationHistoryRule
	7,  // 11: minder.v1alpha.EvaluationHistory.status:type_name -> minder.v1alpha.EvaluationHistoryStatus
	9,  // 12: minder.v1alpha.EvaluationHistory.alert:type_name -> minder.v1alpha.EvaluationHistoryAlert
	8,  // 13: minder.v1alpha.EvaluationHistory.remediation:type_name -> minder.v1alpha.EvaluationHistoryRemediation
	17, // 14: minder.v1alpha.EvaluationHistoryEntity.type:type_name -> minder.v1.Entity
	18, // 15: minder.v1alpha.ListEvaluationResultsResponse.EntityProfileEvaluationResults.profile_status:type_name -> minder.v1.ProfileStatus
	19, // 16: minder.v1alpha.ListEvaluationResultsResponse.EntityProfileEvaluationResults.results:type_name -> minder.v1.RuleEvaluationStatus
	13, // 17: minder.v1alpha.ListEvaluationResultsResponse.EntityEvaluationResults.entity:type_name -> minder.v1.EntityTypedId
	10, // 18: minder.v1alpha.ListEvaluationResultsResponse.EntityEvaluationResults.profiles:type_name -> minder.v1alpha.ListEvaluationResultsResponse.EntityProfileEvaluationResults
	20, // 19: minder.v1alpha.rpc_options:extendee -> google.protobuf.MethodOptions
	21, // 20: minder.v1alpha.rpc_options:type_name -> minder.v1.RpcOptions
	0,  // 21: minder.v1alpha.EvalResultsService.ListEvaluationResults:input_type -> minder.v1alpha.ListEvaluationResultsRequest
	2,  // 22: minder.v1alpha.EvalResultsService.ListEvaluationHistory:input_type -> minder.v1alpha.ListEvaluationHistoryRequest
	1,  // 23: minder.v1alpha.EvalResultsService.ListEvaluationResults:output_type -> minder.v1alpha.ListEvaluationResultsResponse
	3,  // 24: minder.v1alpha.EvalResultsService.ListEvaluationHistory:output_type -> minder.v1alpha.ListEvaluationHistoryResponse
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	20, // [20:21] is the sub-list for extension type_name
	19, // [19:20] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_minder_v1alpha_minder_proto_init() }
func file_minder_v1alpha_minder_proto_init() {
	if File_minder_v1alpha_minder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_minder_v1alpha_minder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListEvaluationResultsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListEvaluationResultsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListEvaluationHistoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListEvaluationHistoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluationHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluationHistoryEntity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluationHistoryRule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluationHistoryStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluationHistoryRemediation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*EvaluationHistoryAlert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListEvaluationResultsResponse_EntityProfileEvaluationResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minder_v1alpha_minder_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ListEvaluationResultsResponse_EntityEvaluationResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_minder_v1alpha_minder_proto_msgTypes[0].OneofWrappers = []any{
		(*ListEvaluationResultsRequest_Profile)(nil),
		(*ListEvaluationResultsRequest_LabelFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_minder_v1alpha_minder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 1,
			NumServices:   1,
		},
		GoTypes:           file_minder_v1alpha_minder_proto_goTypes,
		DependencyIndexes: file_minder_v1alpha_minder_proto_depIdxs,
		MessageInfos:      file_minder_v1alpha_minder_proto_msgTypes,
		ExtensionInfos:    file_minder_v1alpha_minder_proto_extTypes,
	}.Build()
	File_minder_v1alpha_minder_proto = out.File
	file_minder_v1alpha_minder_proto_rawDesc = nil
	file_minder_v1alpha_minder_proto_goTypes = nil
	file_minder_v1alpha_minder_proto_depIdxs = nil
}
