# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

version: '3.2'
services:
  postgres:
    container_name: postgres_container
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_net
  migration:
    build:
      context: ../../
      dockerfile: ./docker/minder/Dockerfile
    command:
      [
        "migrate",
        "up",
        "--yes",
        "--db-host=postgres",
        "--db-name=postgres"
      ]
    volumes:
      - ../migrations:/database/migrations
      - ./output:/output
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_net
  schemaspy:
    image: schemaspy/schemaspy:6.2.4
    volumes:
      - ./output:/output
      - ./config:/config
    container_name: "schemaspy_local"
    depends_on:
      - postgres
      - migration
    network_mode: "service:postgres"
networks:
  app_net:
    driver: bridge
