// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/minder/internal/crypto (interfaces: Engine)
//
// Generated by this command:
//
//	mockgen -package mockcrypto -destination internal/crypto/mock/crypto.go github.com/stacklok/minder/internal/crypto Engine
//

// Package mockcrypto is a generated GoMock package.
package mockcrypto

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// DecryptOAuthToken mocks base method.
func (m *MockEngine) DecryptOAuthToken(arg0 string) (oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptOAuthToken", arg0)
	ret0, _ := ret[0].(oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptOAuthToken indicates an expected call of DecryptOAuthToken.
func (mr *MockEngineMockRecorder) DecryptOAuthToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptOAuthToken", reflect.TypeOf((*MockEngine)(nil).DecryptOAuthToken), arg0)
}

// DecryptString mocks base method.
func (m *MockEngine) DecryptString(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptString indicates an expected call of DecryptString.
func (mr *MockEngineMockRecorder) DecryptString(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptString", reflect.TypeOf((*MockEngine)(nil).DecryptString), arg0)
}

// EncryptOAuthToken mocks base method.
func (m *MockEngine) EncryptOAuthToken(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptOAuthToken", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptOAuthToken indicates an expected call of EncryptOAuthToken.
func (mr *MockEngineMockRecorder) EncryptOAuthToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptOAuthToken", reflect.TypeOf((*MockEngine)(nil).EncryptOAuthToken), arg0)
}

// EncryptString mocks base method.
func (m *MockEngine) EncryptString(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptString", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptString indicates an expected call of EncryptString.
func (mr *MockEngineMockRecorder) EncryptString(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptString", reflect.TypeOf((*MockEngine)(nil).EncryptString), arg0)
}
