name: Build docs cli after merged
on:
  push:
    branches:
      - main
    paths:
      - 'cmd/cli/**'

jobs:
  build-docs-cli:
    runs-on: ubuntu-latest

    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@v3

      # Install Go on the VM running the action.
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      # generate cli docs
      - name: Generate cli docs
        run: make docs