name: docker-compose-lint
on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - 'docker-compose.yaml'
      - '.github/workflows/docker-compose-lint.yml'
permissions:
  contents: read
jobs:
  docker-compose-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint docker-compose.yaml
        run: docker-compose config --quiet
