# SPDX-FileCopyrightText: Copyright 2023 The Minder Authors
# SPDX-License-Identifier: Apache-2.0

# These set of workflows run on every push to the main branch
name: Main
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
permissions:
  contents: read
  packages: write

jobs:
  license-check:
    uses: ./.github/workflows/license-check.yml
  lint:
    permissions: # needed for golangci-lint
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: Allow write access to checks to allow the action to annotate code in the PR.
      checks: write
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
  image-build:
    uses: ./.github/workflows/image-build.yml
  security:
    uses: ./.github/workflows/security.yml
