#
# Copyright 2023 Stacklok, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# These set of workflows run on every pull request
name: PR
on:
  pull_request:

permissions:
  contents: read

jobs:
  license-check:
    uses: ./.github/workflows/license-check.yml
  lint:
    permissions: # needed for golangci-lint
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: Allow write access to checks to allow the action to annotate code in the PR.
      checks: write
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
  test:
    uses: ./.github/workflows/test.yml
  image-build:
    uses: ./.github/workflows/image-build.yml
  security:
    uses: ./.github/workflows/security.yml
  compose-migrate:
    uses: ./.github/workflows/compose-migrate.yml
