name: Add issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          # Add any issues or pull requests to the project board with the labels below
          project-url: https://github.com/orgs/stacklok/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, user-story, enhancement, discuss, needs-docs, security-impact, needs-review
          label-operator: OR